# Generated by Django 2.2.11 on 2020-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenbNedeli',
            fields=[
                ('id_denb_nedeli', models.AutoField(db_column='id_Denb_Nedeli', primary_key=True, serialize=False)),
                ('denb_nedeli', models.CharField(db_column='Denb_Nedeli', max_length=45, verbose_name='День недели')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Дни недели',
                'ordering': ['id_denb_nedeli'],
                'verbose_name': 'День недель',
                'db_table': 'denb_nedeli',
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id_kabinet', models.IntegerField(db_column='id_Kabinet', primary_key=True, serialize=False)),
                ('kabinet', models.CharField(db_column='Kabinet', max_length=45, verbose_name='Номер кабинета')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['id_kabinet'],
                'verbose_name': 'Кабинет',
                'db_table': 'kabinet',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id_klass', models.AutoField(db_column='id_Klass', primary_key=True, serialize=False)),
                ('nomer', models.CharField(db_column='Nomer', max_length=45, verbose_name='Класс')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Классы',
                'ordering': ['id_klass'],
                'verbose_name': 'Класс',
                'db_table': 'klass',
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id_predmet', models.AutoField(db_column='id_Predmet', primary_key=True, serialize=False)),
                ('predmet', models.CharField(db_column='Predmet', max_length=45, verbose_name='Предмет')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Предметы',
                'ordering': ['predmet'],
                'verbose_name': 'Предмет',
                'db_table': 'predmet',
            },
        ),
        migrations.CreateModel(
            name='Prepodavateli',
            fields=[
                ('id_prepodavatelya', models.AutoField(db_column='id_Prepodavatelya', primary_key=True, serialize=False)),
                ('fio', models.CharField(db_column='FIO', max_length=60, verbose_name='ФИО преподавателя')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['fio'],
                'verbose_name': 'Преподаватель',
                'db_table': 'prepodavateli',
            },
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id_raspisanie', models.AutoField(db_column='id_Raspisanie', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_nedeli', 'urok'],
                'verbose_name': 'Расписание',
                'db_table': 'raspisanie',
            },
        ),
        migrations.CreateModel(
            name='Uroki',
            fields=[
                ('id_uroka', models.AutoField(db_column='id_Uroka', primary_key=True, serialize=False)),
                ('nom_uroka', models.IntegerField(db_column='Nom_Uroka', verbose_name='Номер урока')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Уроки',
                'ordering': ['nom_uroka'],
                'verbose_name': 'Урок',
                'db_table': 'uroki',
            },
        ),
    ]
