# Generated by Django 2.2.11 on 2020-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='DenbNedeli',
            fields=[
                ('id_denb_nedeli', models.AutoField(db_column='id_Denb_Nedeli', primary_key=True, serialize=False)),
                ('denb_nedeli', models.CharField(db_column='Denb_Nedeli', max_length=45, verbose_name='День недели')),
            ],
            options={
                'verbose_name_plural': 'Дни недели',
                'ordering': ['id_denb_nedeli'],
                'verbose_name': 'День недель',
                'managed': False,
                'db_table': 'denb_nedeli',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Kabinet',
            fields=[
                ('id_kabinet', models.IntegerField(db_column='id_Kabinet', primary_key=True, serialize=False)),
                ('kabinet', models.CharField(db_column='Kabinet', max_length=45, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['id_kabinet'],
                'verbose_name': 'Кабинет',
                'managed': False,
                'db_table': 'kabinet',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id_klass', models.AutoField(db_column='id_Klass', primary_key=True, serialize=False)),
                ('nomer', models.CharField(db_column='Nomer', max_length=45, verbose_name='Класс')),
            ],
            options={
                'verbose_name_plural': 'Классы',
                'ordering': ['id_klass'],
                'verbose_name': 'Класс',
                'managed': False,
                'db_table': 'klass',
            },
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id_predmet', models.AutoField(db_column='id_Predmet', primary_key=True, serialize=False)),
                ('predmet', models.CharField(db_column='Predmet', max_length=45, verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Предметы',
                'ordering': ['predmet'],
                'verbose_name': 'Предмет',
                'managed': False,
                'db_table': 'predmet',
            },
        ),
        migrations.CreateModel(
            name='Prepodavateli',
            fields=[
                ('id_prepodavatelya', models.AutoField(db_column='id_Prepodavatelya', primary_key=True, serialize=False)),
                ('fio', models.CharField(db_column='FIO', max_length=60, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['fio'],
                'verbose_name': 'Преподаватель',
                'managed': False,
                'db_table': 'prepodavateli',
            },
        ),
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id_raspisanie', models.AutoField(db_column='id_Raspisanie', primary_key=True, serialize=False)),
                ('day_nedeli', models.IntegerField(db_column='Day_Nedeli')),
                ('urok', models.IntegerField(db_column='Urok')),
                ('klass', models.IntegerField(db_column='Klass')),
                ('r_predmet', models.IntegerField(db_column='R_Predmet')),
                ('kabinet', models.IntegerField(db_column='Kabinet')),
                ('prepodavatel', models.IntegerField(db_column='Prepodavatel')),
            ],
            options={
                'managed': False,
                'db_table': 'raspisanie',
            },
        ),
        migrations.CreateModel(
            name='Uroki',
            fields=[
                ('id_uroka', models.AutoField(db_column='id_Uroka', primary_key=True, serialize=False)),
                ('nom_uroka', models.IntegerField(db_column='Nom_Uroka', verbose_name='Номер урока')),
            ],
            options={
                'verbose_name_plural': 'Уроки',
                'ordering': ['nom_uroka'],
                'verbose_name': 'Урок',
                'managed': False,
                'db_table': 'uroki',
            },
        ),
    ]
