# Generated by Django 2.2.11 on 2020-03-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspisanie',
            options={'managed': False, 'ordering': ['day_nedeli', 'urok'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
